# ————合并test_login.py和test_openapp.py文件进行执行————success——

import unittest
from test_mwgx import test_config
from test_mwgx import test_login
from test_mwgx import test_buy
import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_config.SetConfig))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_buy.BuyTest))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_login.LoginTest))

    #     # 测试报告生成方法一：这一步是在当前文件夹里自动生成一个txt格式的测试报告，测试报告名称就叫：UnittestTextReport.txt.
    # with open('./UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    # 测试报告生成方法二：这一步是在当前文件夹中自动生成一个html格式的测试报告，报告名称是：HTMLReport.html，需要使用浏览器打开查看
    with open('HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner.HTMLTestRunner(stream=f,
                                               title='HLJ Test Report',
                                               description='generated by HTMLTestRunner.',
                                               verbosity=2
                                               )
        runner.run(suite)
